name: CI for Vite + React App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        working-directory: ./mrDverkinFront

      - name: Run linter
        run: npm run lint
        working-directory: ./mrDverkinFront

      - name: Build the app
        run: npm run build
        working-directory: ./mrDverkinFront
