name: CI for Vite + React App

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Build the app
        run: npm run build

      - name: Check contents of dist
        run: ls -la dist

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            echo "🚀 Начало деплоя"
            
            cd ~/mrDverkinFront
            
            echo "🔁 Сброс локальных изменений"
            git reset --hard HEAD
            git clean -fd
            
            echo "📥 Получаем свежий код"
            git pull origin master
            if [ $? -ne 0 ]; then echo "❌ git pull не удался"; exit 1; fi
            
            echo "🧹 Удаляем старые фронтенд-файлы"
            sudo rm -f /var/www/frontend/index.html
            sudo rm -rf /var/www/frontend/assets
            
            echo "📦 Копируем новые файлы"
            sudo cp -r ~/mrDverkinFront/dist/* /var/www/frontend/
            
            echo "🔍 Проверка конфигурации nginx"
            sudo nginx -t
            if [ $? -ne 0 ]; then echo "❌ Ошибка в конфиге nginx"; exit 1; fi
            
            echo "🔄 Перезапуск nginx"
            sudo systemctl restart nginx
            if [ $? -ne 0 ]; then echo "❌ Не удалось перезапустить nginx"; exit 1; fi
            
            echo "✅ Деплой завершён успешно!"